api/urls.py
from django.urls import path
from .views import ProductoList, ProductoDetalle

urlpatterns = [


    path('productos/',ProductoList.as_view(),name='producto_api'),
    path('productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_api_detalle'),

]

compra/urls.py
from django.urls import path, include

from .views import  PerfilView,ProveedorView,ProveedorNew, ProveedorEdit,\
    ComprasView, compras, CompraDetDelete, CompraEncDelete, pago_compra
from .reportes import imprimir_factura_compra,imprimir_factura_list,imprimir_general_proveedor


urlpatterns = [
    path('proveedores/',ProveedorView.as_view(), name="lista_proveedor"),
    path('proveedores/perfil/<int:id>',PerfilView.as_view(), name="perfil_proveedor"),
    path('proveedores/nuevo',ProveedorNew.as_view(), name="nuevo_proveedor"),
    path('proveedores/edit/<pk>',ProveedorEdit.as_view(), name="editar_proveedor"),
    path('proveedores/general/<int:id>/imprimir', imprimir_general_proveedor,name="imprimir_general_proveedor"),

    path('factura/',ComprasView.as_view(), name="lista_compras"),
    path('factura/new/',compras, name="nueva_compra"),
    path('factura/edit/<int:compra_id>',compras, name="editar_compra"),
    path('factura/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="eliminar_compra"),
    path('factura/eliminar/<int:pk>',CompraEncDelete.as_view(), name="eliminar_enc"),

    path('factura/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),
    path('factura/compras/<int:id>/imprimir', imprimir_factura_compra,name="imprimir_factura_compra"),
    path('factura/pago_compra/<int:id>',pago_compra, name="pago_compra"),
    
]

remetal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('base.urls','base'), namespace='base')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('compra/',include(('compra.urls','compra'), namespace='compra')),
    path('facturacion/',include(('facturacion.urls','facturacion'), namespace = 'facturacion')),
    path('api/',include(('api.urls','api'), namespace = 'api')),
    path('admin/', admin.site.urls),
]

compra/forms.py
from django import forms
from django.shortcuts import HttpResponse
from .models import Proveedor, ComprasEnc


class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        exclude = ['um', 'fm', 'uc', 'fc']
        fields = ['razon_social',
                  'tipo',
                  'rif',
                  'direccion',
                  'direccion2',
                  'telefono',
                  'email']
        labels = {'direccion': "Direccion Principal", 'direccion2': "Direccion Secundaria(Opcional)",
                  'telefono': "Numero Telefonico", 'email': "Correo Electronico"}
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    def clean(self):
        try:
            sc = Proveedor.objects.get(
                razon_social=self.cleaned_data["razon_social"]
            )
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk!=sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data
        
class ComprasEncForm(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()

    class Meta:
        model = ComprasEnc
        fields = ['proveedor', 'observacion',
                  'no_factura', 'sub_total','descuento',
                  'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['no_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True
        self.fields['observacion'].widget.attrs.update(
            {'style': 'height: calc(1.5em + 0.75rem + 2px);'})
        self.fields['proveedor'].widget.attrs.update(
            {"class": "form-select", "id": "proveedor"})

compra/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Proveedor, ComprasEnc, ComprasDet, Producto
from .forms import ProveedorForm, ComprasEncForm
from django.db.models import Sum
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from base.views import SinPrivilegios
import datetime

class PerfilView(SinPrivilegios, ListView):
    permission_required="facturacion.view_cliente"
    model = Proveedor
    template_name = "compra/proveedor/perfil_proveedor.html"

    def get(self, request,id, *args, **kwargs):
        proveedor = Proveedor.objects.filter(id=id)
        enc = ComprasEnc.objects.filter(proveedor=id,pagado=True)
        context = {
            'proveedor':proveedor,
            'enc':enc,
        }
        return render(request, self.template_name, context)


class ProveedorView(SinPrivilegios, ListView):
    model = Proveedor
    template_name = "compra/proveedor/proveedor_list.html"
    context_object_name = "obj"
    permission_required="compra.view_proveedor"

class ProveedorNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model = Proveedor
    template_name = "compra/proveedor/proveedor_form.html"
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_message="Proveedor Creado Correctamente"
    success_url= reverse_lazy("compra:nueva_compra")
    permission_required = "compra.add_proveedor"
    
    def post(self, request, *args, **kwargs):
        form = self.form_class()
        form_data = request.POST or None
        form_post = self.form_class(form_data)
        if request.method == 'POST':
            if 'rif' in request.POST:
                rif = request.POST['rif'].upper()
                desc = Proveedor.objects.filter(rif=rif).exists()
                if desc ==  True:
                    messages.error(request,'Ya Existe un Proveedor Registrado con Ese Rif.')
                    return redirect("compra:nueva_compra")
                else:
                    self.form_valid(form_post)
                    return redirect("compra:nueva_compra")
            return render(request, self.template_name, {'form': form})
            
    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.estado = True
        return super().form_valid(form)

class ProveedorEdit(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Proveedor
    template_name="compra/proveedor/proveedor_form.html"
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_message="Proveedor Editado Correctamente"
    fail_message="Proveedor existe"
    success_url= reverse_lazy("compra:nueva_compra")
    permission_required = "compra.change_proveedor"
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class ComprasView(SinPrivilegios, ListView):
    model = ComprasEnc
    template_name = "compra/compras/compras_list.html"
    context_object_name = "obj"
    permission_required="compra.view_comprasenc"
    
    def get(self,request):
        enc2 = ComprasEnc.objects.filter(pagado=True)
        enc = ComprasEnc.objects.filter(pagado=False)
        contexto = {'obj':enc,'obj2':enc2}
        return render(request,self.template_name,contexto)


@login_required(login_url='/login/')
@permission_required('compra.view_comprasenc', login_url='bases:sin_privilegios')
def compras(request,compra_id=None):
    template_name="compra/compras/compras.html"
    prod=Producto.objects.filter(estado=True)
    form_compras={}
    contexto={}
    if request.method=='GET':
        #codigo de facturacion
        proveedores = Proveedor.objects.filter(estado=True)
        try:
            cod = ComprasEnc.objects.latest('id')
            c ={'no_factura': f"RM-C-{cod.id+1}"}
            form_compras=ComprasEncForm(c)
        except:
            cod = 0
            c ={'no_factura': f"RM-C-{cod+1}"}
            form_compras=ComprasEncForm(c)
        enc = ComprasEnc.objects.filter(pk=compra_id).first()
        if enc:
            det = ComprasDet.objects.filter(compra=enc)
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            fecha_factura = datetime.date.isoformat(enc.fecha_factura)
            e = {
                'proveedor': enc.proveedor,
                'observacion': enc.observacion,
                'no_factura': f"RM-C-{enc.id}",
                'sub_total': enc.sub_total,
                'descuento': enc.descuento,
                'total':enc.total
            }
            form_compras = ComprasEncForm(e)
        else:
            det=None
        contexto={'productos':prod,'encabezado':enc,'detalle':det,'form_enc':form_compras,"proveedores":proveedores}

    if request.method=='POST':
        fecha_compra = request.POST.get("fecha_compra")
        observacion = request.POST.get("observacion")
        no_factura = request.POST.get("no_factura")
        fecha_factura = request.POST.get("fecha_factura")
        proveedor = request.POST.get("enc_proveedor")
        sub_total = 0
        descuento = 0

        if not compra_id:
            prov=Proveedor.objects.get(pk=proveedor)
            enc = ComprasEnc(
                fecha_compra=fecha_compra,
                observacion=observacion,
                no_factura=no_factura,
                fecha_factura=fecha_factura,
                proveedor=prov,
                uc = request.user 
            )
            if enc:
                enc.save()
                compra_id=enc.id
        else:
            enc=ComprasEnc.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra = fecha_compra
                enc.observacion = observacion
                enc.no_factura=no_factura
                enc.fecha_factura=fecha_factura
                enc.um=request.user.id
                enc.save()
        if not compra_id:
            return redirect("compra:lista_compras")
        
        producto = request.POST.get("id_id_producto")
        if producto == "":
            messages.error(request,'No ha Agregado Producto.')
            return redirect("compra:editar_compra",compra_id=compra_id)

        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        descuento_detalle  = request.POST.get("id_descuento_detalle")
        prod = Producto.objects.get(pk=producto)
        det = ComprasDet(
            compra=enc,
            producto=prod,
            cantidad=cantidad,
            precio_prv=precio,
            descuento=descuento_detalle,
            costo=0,
            uc = request.user
        )
        if det:
            det.save()
            sub_total=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total = sub_total["sub_total__sum"]
            enc.descuento=descuento["descuento__sum"]
            enc.save()
        return redirect("compra:editar_compra",compra_id=compra_id)


    return render(request, template_name, contexto)

@login_required(login_url='/login/')
@permission_required('compra.add_comprasenc', login_url='bases:sin_privilegios')
def pago_compra(request, id):
    template_name = "compra/compras/pagar_compra.html"
    enc = ComprasEnc.objects.get(pk=id)
    if request.method=="GET":
        context={"det":enc}
    if request.method == "POST":
        metodo = request.POST.get("metodo")
        monto = request.POST.get("monto")
        if metodo == "":
            return HttpResponse('No ha Seleccionado el Metodo de Pago.')
        if float(monto) < enc.total:
            enc.abono = True
            enc.tipo_pago = metodo
            enc.monto = float(monto)
            enc.user_cobra = request.user.username
            enc.save_abono_monto()
            return HttpResponse("ok")
        else:
            enc.pagado = True
            enc.tipo_pago = metodo
            enc.monto = float(monto)
            enc.user_cobra = request.user.username
            enc.save()

            return HttpResponse("ok")

        
    
    return render(request,template_name,context)



class CompraDetDelete(SinPrivilegios, DeleteView):
    permission_required = "compra.delete_comprasdet"
    model = ComprasDet
    template_name = "compra/compras/compra_eliminar.html"
    context_object_name = 'obj'
    
    def get_success_url(self):
          compra_id=self.kwargs['compra_id']
          return reverse_lazy('compra:editar_compra', kwargs={'compra_id': compra_id})


class CompraEncDelete(SinPrivilegios, DeleteView):
    permission_required = "compra.delete_comprasenc"
    model = ComprasEnc
    template_name = "compra/compras/eliminar_enc.html"
    context_object_name = 'obj'
    success_message="Compra Eliminada"
    success_url= reverse_lazy("compra:lista_compras")
    

compra/templates/compra/proveedor/perfil_proveedor.html
{% extends 'padre/base.html' %} 
{% block page_content %} 

<div class="row">
  <div class="col-md-12">
    <div class="card py-4 px-3"> 
      <div class="">
        {% for item in proveedor %}
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="name mt-3 fs-4">Razon Social: {{ item.razon_social }}</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd fs-5">RIF / C.I.: {{ item.rif }}</span> 
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd1 fs-5">Direccion Principal: {{ item.direccion }}</span> 
          </div>
        </div>
        {% if item.direccion2 == None %}
        {% else %}
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd1 fs-5">Direccion Secundaria:{{ item.direccion2 }}</span>  
          </div>
        </div>
        {% endif %}
        <div class="row">
          <div class="col-md-12">
            <div class="date fs-5"> <span class="join">Registrado: {{ item.fc|date:"d/m/Y" }}</span></div>  
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mt-4">
            <a class="btn btn-primary btn-circle" title="Imprimir historial" href="{% url 'compra:imprimir_general_proveedor' item.id%}" target="reportes">
              Imprimir historial
            </a>  
          </div>
        </div>
        
        <div class="text mt-3"> 
          <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-toolbar=".buttons-toolbar" data-locale="es-MX" data-sort-order="desc">
            <thead align="center">
                <tr>
                    <th>No. Factura</th>
                    <th>Proveedor</th>
                    <th>Observacion</th>
                    <th>Fecha</th>
                    <th>Gastos Adic</th>
                    <th>Total</th>
                    <th>Pagado</th>
                    <th>Imprimir</th>
                </tr>
            </thead>
            <tbody align="center">
                {% for item2 in enc %}
                <tr>
                    <td>{{ item2.no_factura }}</td>
                    <td>{{ item2.proveedor }}</td>
                    <td>{{ item2.observacion }}</td>
                    <td>{{ item2.fecha_factura | date:"d/m/Y" }}</td>
                    <td>{{ item2.descuento|floatformat:2 }}$</td>
                    <td>{{ item2.total|floatformat:2 }}$</td>
                    <td>{% if item2.pagado %}
                    <i class="fa fa-circle-check text-success"></i>
                    {% else %}
                      <i class="fa fa-circle-xmark text-danger"></i>
                    {% endif %}</td>
                    <td><a
                      class="btn btn-sm btn-success btn-circle"
                      title="Imprimir"
                      href="{% url 'compra:imprimir_factura_compra' item2.id%}"
                      target="reportes"
                      ><i class="fas fa-print"></i
                    ></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            
            {% endfor %}
          </div> 
        </div>
    </div>
  </div>
</div>
          
 {% endblock %}

compra/templates/compra/proveedor/proveedor_form.html
<div class="modal-dialog modal-md">
    <div class="modal-content">
        {% if obj %}
        <form role="form" id='frmProveedor'action="{% url 'compra:editar_proveedor' obj.id %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" id='frmProveedor'action="{% url 'compra:nuevo_proveedor' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Proveedor
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-danger" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>  

<script>
$(function() {
    $("#frmProveedor").submit(function( e ) {
        var frm = $('#frmProveedor');
        // alert("{{request.path}}")
        $.ajax({
                type: frm.attr('method'),
                // url: frm.attr('action'),
                url: "{{request.path}}",
                data: frm.serialize(),
                success: function (data) {
                    // alert(data);
                    // window.location.reload(true);
                    $("#id").val(data)
                    console.log(data)
                    cerrar_modal()
                },
                error: function(data,b,c) {
                    alert(data);
                    console.log(c)
                }
            });
            return false;
    });
</script>

compra/templates/compra/proveedor/proveedor_list.html
{% extends 'padre/base.html' %}

{% block page_content %}
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedores</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info">No hay Proveedores Registrados</div>
      {% endif %}
      <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-toolbar=".buttons-toolbar" data-locale="es-MX" data-sort-order="desc">
        <thead align="center">
          <th>Id</th>
          <th>Razon Social</th>
          <th>Rif</th>
          <th>Dirección</th>
          <th>Teléfono</th>
          <th>Email</th>
          <th class="all">Ver Perfil</th>
        </thead>
        <tbody align="center">
          {% for item in obj %}
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.razon_social}}</td>
              <td>{{ item.rif }}</td>
              <td>{{ item.direccion }}</td>
              <td>{{ item.telefono }}</td>
              <td>{{ item.email }}</td>
              <td>
                <a
                class="btn btn-sm btn-success btn-circle"
                title="Ver perfil"
                href="{% url 'compra:perfil_proveedor' item.id%}"
                ><i class="fas fa-user"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}