api/urls.py
from django.urls import path
from .views import ProductoList, ProductoDetalle

urlpatterns = [


    path('productos/',ProductoList.as_view(),name='producto_api'),
    path('productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_api_detalle'),

]

inventario/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, inhabilitarcat,\
    SubCategoriaNew, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, inhabilitarsubcat, \
    ProductoView, ProductoNew, ProductoEdit, inhabilitarproducto,\
    GastosView, GastosNew, GastosEdit, inhabilitargasto, SearchResultsView
from .reporte import imprimir_todo_producto, imprimir_gastos


urlpatterns = [
     
     path("search/", SearchResultsView.as_view(), name="search_results"),
    # vistas listas urls
    path('categorias/', CategoriaView.as_view(), name="lista_categoria"),
    path('categoria/nueva', CategoriaNew.as_view(), name='nueva_categoria'),
    path('categoria/editar/<pk>', CategoriaEdit.as_view(), name='editar_categoria'),
    path('categoria/estado/<int:id>', inhabilitarcat,
         name='inhabilitar_categoria'),


    path('subcategorias/', SubCategoriaView.as_view(), name="lista_subcategoria"),
    path('subcategorias/nueva', SubCategoriaNew.as_view(),
         name='nueva_subcategoria'),
    path('subcategoria/editar/<pk>', SubCategoriaEdit.as_view(),
         name='editar_subcategoria'),
    path('subcategoria/estado/<int:id>', inhabilitarsubcat,
         name='inhabilitar_subcategoria'),



    path('producto/', ProductoView.as_view(), name="lista_productos"),
    path('producto/nuevo', ProductoNew.as_view(), name='nuevos_productos'),
    path('producto/editar/<pk>', ProductoEdit.as_view(), name='editar_productos'),
    path('producto/estado/<int:id>', inhabilitarproducto,
         name='inhabilitar_producto'),
    path('producto/imprimir-todas/<str:f1>/<str:f2>',
         imprimir_todo_producto, name="imprimir_producto"),


    path('gastos/', GastosView.as_view(), name="lista_gastos"),
    path('gastos/nueva', GastosNew.as_view(),
         name='nuevo_gastos'),
    path('gastos/editar/<pk>', GastosEdit.as_view(),
         name='editar_gastos'),
    path('gastos/estado/<int:id>', inhabilitargasto,
         name='inhabilitar_gastos'),
     path('gastos/imprimir-todas/<str:f1>/<str:f2>',
         imprimir_gastos, name="imprimir_gastos"),


]

remetal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('base.urls','base'), namespace='base')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('compra/',include(('compra.urls','compra'), namespace='compra')),
    path('facturacion/',include(('facturacion.urls','facturacion'), namespace = 'facturacion')),
    path('api/',include(('api.urls','api'), namespace = 'api')),
    path('admin/', admin.site.urls),
]

inventario/models.py
from django.db import models
from base.models import BaseModelo
# Create your models here.

class Categoria(BaseModelo):
    SEL='Seleccion Una Opcion:'
    MAT='MATERIAL'
    GAS='GASTOS'
    OTR='OTRO'
    TIPO = [
        (SEL,'Seleccion Una Opcion:'),
        (MAT,'MATERIAL'),
        (GAS,'GASTOS'),
        (OTR,'OTRO')
    ]
    title=models.CharField(
        max_length=25,
        choices=TIPO,
        default=SEL
    )
    descripcion = models.CharField(
        max_length=100,
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural= "Categorias"

class SubCategoria(BaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Categoría'
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion,self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural= "Sub Categorias"
        unique_together = ('categoria','descripcion')

class Producto(BaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True,
        blank=True,
        null=True)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.FloatField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="images/",null=True,blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()
   

    
    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'descripcion')


class Gastos(BaseModelo):
    descripcion = models.CharField(max_length=250,blank=True,null=True)
    monto_gastos = models.FloatField(default=0)
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField()
    fm = models.DateTimeField(auto_now=True)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Gastos, self).save()

    class Meta:
        verbose_name_plural = "Gastos de Compras"
        verbose_name="Gastos de Compra"

inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, CreateView, UpdateView,DeleteView
from .models import Categoria, SubCategoria, Producto, Gastos
from .forms import CategoriaForm, SubCategoriaForm, ProductoForm, GastosForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from base.views import SinPrivilegios
from django.contrib import messages
from django.db.models import Q
from django.db.models import Sum

#Vistas de Categoria crear, editar eliminar y ver el listadp
class CategoriaView(SinPrivilegios,ListView):
    permission_required = "inventario.view_categoria"
    model = Categoria
    template_name = "inventario/categoria/categoria_list.html"
    context_object_name = 'obj'
    
class CategoriaNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    permission_required="inventario.add_categoria"
    model=Categoria
    template_name="inventario/categoria/categoria_form.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_message="Categoria Creada Satisfactoriamente"
    success_url=reverse_lazy("inventario:lista_categoria")
    permission_required="inventario.add_categoria"
    
    def post(self, request, *args, **kwargs):
        form = self.form_class()
        form_data = request.POST or None
        form_post = self.form_class(form_data)
        if request.method == 'POST':
            if 'descripcion' in request.POST:
                descripcion = request.POST['descripcion'].upper()
                desc = Categoria.objects.filter(descripcion=descripcion).exists()
                if desc ==  True:
                    messages.error(request,'Ya Existe una Categoria con la Misma Descripcion.')
                    return redirect("inventario:lista_categoria")
                else:
                    self.form_valid(form_post)
                    return redirect("inventario:lista_categoria")
            return render(request, self.template_name, {'form': form})
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.estado = True
        return super().form_valid(form)


class CategoriaEdit(SuccessMessageMixin,SinPrivilegios,UpdateView):
    permission_required="inventario.change_categoria"
    model=Categoria
    template_name="inventario/categoria/categoria_form.html"
    context_object_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inventario:lista_categoria")
    success_message="Categoria Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inventario.change_categoria', login_url='base:sin_privilegios')
def inhabilitarcat(request, id):
    categoria = Categoria.objects.filter(pk=id).first()

    if request.method=="POST":
        if categoria:
            categoria.estado = not categoria.estado
            categoria.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    
    return HttpResponse("FAIL")

#Vistas de Categoria crear, editar eliminar y ver el listado


class SubCategoriaView(SinPrivilegios,ListView):
    permission_required = "inventario.view_subcategoria"
    model = SubCategoria
    template_name = "inventario/subcategoria/subcategoria_list.html"
    context_object_name = 'obj'

class SubCategoriaNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=SubCategoria
    template_name="inventario/subcategoria/subcategoria_form.html"
    context_object_name = "obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inventario:lista_subcategoria")
    success_message="Sub Categoría Creada Satisfactoriamente"
    permission_required="inventario.add_subcategoria"

    def post(self, request, *args, **kwargs):
        form = self.form_class()
        form_data = request.POST or None
        form_post = self.form_class(form_data)
        if request.method == 'POST':
            if 'descripcion' in request.POST:
                descripcion = request.POST['descripcion'].upper()
                desc = SubCategoria.objects.filter(descripcion=descripcion).exists()
                if desc ==  True:
                    messages.error(request,'Ya Existe una Sub-Categoria con la Misma Descripcion.')
                    return redirect("inventario:lista_subcategoria")
                else:
                    self.form_valid(form_post)
                    return redirect("inventario:lista_subcategoria")
            return render(request, self.template_name, {'form': form})

    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.estado = True
        return super().form_valid(form)


class SubCategoriaEdit(SuccessMessageMixin,SinPrivilegios, UpdateView):
    model=SubCategoria
    template_name="inventario/subcategoria/subcategoria_form.html"
    context_object_name = "obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inventario:lista_subcategoria")
    success_message="Sub Categoría Actualizada Satisfactoriamente"
    permission_required="inventario.change_subcategoria"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inventario.change_subcategoria', login_url='base:sin_privilegios')
def inhabilitarsubcat(request, id):
    subcategoria = SubCategoria.objects.filter(pk=id).first()

    if request.method=="POST":
        if subcategoria:
            subcategoria.estado = not subcategoria.estado
            subcategoria.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    
    return HttpResponse("FAIL")



class ProductoView(SinPrivilegios,ListView):
    model = Producto
    template_name = "inventario/producto/producto_list.html"
    context_object_name = "obj"
    permission_required="inventario.view_producto"


class ProductoNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Producto
    template_name="inventario/producto/producto_form.html"
    context_object_name = 'obj'
    form_class=ProductoForm
    success_url= reverse_lazy("inventario:lista_productos")
    success_message="Producto Creado Correctamente"
    permission_required="inventario.add_producto"
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.estado = True
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(ProductoNew, self).get_context_data(**kwargs)
        try:
            codigo = Producto.objects.latest('id')
            context["codigo"] = codigo.id + 1
        except:
            codigo = 0
            context["codigo"] = codigo + 1
        
        context["producto"] = Producto.objects.all()
        context["categorias"] = Categoria.objects.filter(title__icontains='MATERIAL')
        context["subcategorias"] = SubCategoria.objects.all()
        return context



class ProductoEdit(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Producto
    template_name="inventario/producto/producto_form.html"
    context_object_name = 'obj'
    form_class=ProductoForm
    success_url= reverse_lazy("inventario:lista_productos")
    success_message="Producto Editado Correctamente"
    permission_required="inventario.change_producto"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(ProductoEdit, self).get_context_data(**kwargs)
        context["categorias"] = Categoria.objects.filter(title__icontains='MATERIAL')
        context["subcategorias"] = SubCategoria.objects.all()
        context["obj"] = Producto.objects.filter(pk=pk).first()
        context["codigo"] = pk

        return context


@login_required(login_url='/login/')
@permission_required('inventario.change_producto', login_url='base:sin_privilegios')
def inhabilitarproducto(request, id):
    producto = Producto.objects.filter(pk=id).first()

    if request.method=="POST":
        if producto:
            producto.estado = not producto.estado
            producto.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    
    return HttpResponse("FAIL")


class GastosView(SinPrivilegios,ListView):
    permission_required = "inventario.view_gastos"
    model = Gastos
    template_name = "inventario/gastos/gastos_list.html"
    context_object_name = 'obj'

class GastosNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Gastos
    template_name="inventario/gastos/gastos_form.html"
    context_object_name = "obj"
    form_class=GastosForm
    success_url=reverse_lazy("inventario:lista_gastos")
    success_message="Nuevo Gasto Registrado Satisfactoriamente"
    permission_required="inventario.add_gastos"

    def get_context_data(self, **kwargs):
        context = super(GastosNew, self).get_context_data(**kwargs)
        
        context["categorias"] = Categoria.objects.filter(title__icontains='GASTOS')
        context["subcategorias"] = SubCategoria.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class()
        form_data = request.POST or None
        form_post = self.form_class(form_data)
        if request.method == 'POST':
            if 'descripcion' in request.POST:

inventario/templates/inventario/subcategoria/inhabilitar.html
<div class="modal-dialog modal-sm">
  <div class="modal-content">
      <form method="POST" class="form-inline">
          {% csrf_token %}
          <div class="col">
              <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase">
                          <div class="alert">
                              ¿ Inactivar <b>{{ obj.descripcion }} </b> ?
                          </div>
                      </div>
                    </div>
                    <div class="row">
                      <button type="button" class="btn btn-danger" id="btnInactivar"><i class="far fa-question-circle"></i>Si, Inactivar</button>
                      <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                          No, Cancelar
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </form>
  </div>
</div>

<script>
$(document).ready(function(){

  var token = $('input[name=csrfmiddlewaretoken]').val();
  $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
    });

  $("#btnInactivar").click(function(e){
      e.preventDefault();
      //alert("Probando");

      var id = {{ obj.id }};
      var template="{% url 'inventario:inhabilitar_subcategoria' obj.id %}";
      //template += id;
      var data = {"id":id};
      data = JSON.stringify(data);

      $.ajax({
        type: "POST",
        url: template,
        data: data,
        beforeSend: function(xhr,settings){
          $.ajaxSettings.beforeSend(xhr,settings);
        },
        success: function(response){
          console.log(response);
          cerrar_modal();
          //alert(response);
          var tipo=(response.startsWith('SubCategoria no existe') ? 'red':'green' );
          mensaje(response,tipo);
        },
        error: function(jqXHR, textStatus, errorThrow){
          console.log(textStatus, errorThrow);
          mensaje(errorThrow,'red');
          cerrar_modal();
        }
      });
  });

});
</script>

inventario/templates/inventario/subcategoria/subcategoria_form.html
<div class="modal-dialog modal-md">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:editar_subcategoria' obj.pk %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inventario:nueva_subcategoria' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Sub-Categoria
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {#{ form.as_p }#}
                        </div>
                        <div class="row">
                            <div class="mb-3">
                                <label for="id_categoria" class="form-label">{{form.categoria.label}}</label>
                                {{form.categoria}}
                            </div>                   
                        </div>
                        <div class="row">
                            <div class="mb-3">
                                <label for="id_descripcion" class="form-label">{{form.descripcion.label}}</label>
                                {{form.descripcion}}
                            </div>                        
                        </div>


                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                
                                <button type="button" class="btn btn-danger" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>


inventario/templates/inventario/subcategoria/subcategoria_list.html
{% extends 'padre/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorías</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="buttons-toolbar">
        <a class="btn btn-primary mb-3" onclick="return abrir_modal('{% url 'inventario:nueva_subcategoria' %}')" href="#"><i class="fa-solid fa-circle-plus"></i> Nuevo</a>
      </div>
      {% if not obj %}
      <div class="alert alert-info">No hay Sub categorías Registradas</div>
      {% else %}
     
      <table 
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-MX"
      data-sort-name="id"
      data-sort-order="desc"
    >
          <thead align="center">
              <th data-field='id'>Id</th>
              <th data-field='categoria'>Categoria</th>
              <th data-field='descripcion'>Descripción</th>
              <th data-field='estado'>Estado</th>
              <th data-field='fc'>F. Creado</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody align="center">
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.categoria }}</td>
                <td>{{ item.descripcion }}</td>
                <td >{#item.estado|yesno:"Activo,Inactivo"#}
                  <div class="cursor-pointer">
                      {% if item.estado %}
                      <i class="fa fa-circle-check text-success"></i>
                    {% else %}
                      <i class="fa fa-circle-xmark text-danger"></i>
                    {% endif %}
                  </div>
                </td>
                <td>{{ item.fc|date:"d/m/Y" }}</td>
                <td>
                  <button class="btn btn-sm btn-warning btn-circle" title="Editar" onclick="return abrir_modal('{% url 'inventario:editar_subcategoria' item.id %}')">
                    <i class="far fa-edit"></i></button>
                </td>
            </tr>
            {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  function inactivar(id)
  {
    var data = {id:id};
    data = JSON.stringify(data);
    var token = '{{csrf_token}}';
    // alert(token);
    // alert(id);
    
    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:"/inventario/subcategoria/estado/"+id,
      data: data,
      success: function(response){
        if(response==="OK")
        {
          location.reload(true);
        }
        else{
          mensaje("Error Intentado Cambiar Estado a la SubCategoria");
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        mensaje(errorThrow,'red');
        cerrar_modal();
      }
    });
  }
  </script>
{% endblock %}