api/urls.py
from django.urls import path
from .views import ProductoList, ProductoDetalle

urlpatterns = [


    path('productos/',ProductoList.as_view(),name='producto_api'),
    path('productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_api_detalle'),

]

facturacion/urls.py
from django.urls import path
from .views import  PerfilView ,ClienteView, ClienteNew, ClienteEdit,\
    FacturaView, facturas, ProductoView, borrar_detalle_factura, FacturaEncDelete, pago_factura, desecho
from .reportes import imprimir_factura_recibo,imprimir_factura_list,imprimir_general_cliente

urlpatterns = [
    path('clientes/',ClienteView.as_view(), name="lista_cliente"),
    path('clientes/perfil/<int:id>',PerfilView.as_view(), name="perfil_cliente"),
    path('clientes/new',ClienteNew.as_view(), name="nuevo_cliente"),
    path('clientes/edit/<int:pk>',ClienteEdit.as_view(), name="editar_cliente"),
    path('clientes/imprimir/<int:id>',imprimir_general_cliente, name="imprimir_general_cliente"),

    path('factura/',FacturaView.as_view(), name="lista_factura"),
    path('factura/new',facturas, name="nueva_factura"),
    path('factura/edit/<int:id>',facturas, name="editar_factura"),
    path('eliminar/<int:pk>',FacturaEncDelete.as_view(), name="eliminar_enc"),
    path('eliminar/desecho/<int:id>',desecho, name="desecho"),
    path('factura/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
    path('factura/pago_factura/<int:id>',pago_factura, name="pago_factura"),
    
    
    path('factura/buscar-producto',ProductoView.as_view(), name="factura_producto"),
    path('factura/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_one"),
    path('factura/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),




]

remetal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('base.urls','base'), namespace='base')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('compra/',include(('compra.urls','compra'), namespace='compra')),
    path('facturacion/',include(('facturacion.urls','facturacion'), namespace = 'facturacion')),
    path('api/',include(('api.urls','api'), namespace = 'api')),
    path('admin/', admin.site.urls),
]

facturacion/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['razon_social',
                  'tipo',
                  'rif',
                  'direccion',
                  'direccion2',
                  'telefono',
                  'email']
        exclude = ['um', 'fm', 'uc', 'fc']
        labels = {'direccion': "Direccion Principal", 'direccion2': "Direccion Secundaria(Opcional)",
                  'telefono': "Numero Telefonico", 'email': "Correo Electronico"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    def clean(self):
        try:
            sc = Cliente.objects.get(
                razon_social=self.cleaned_data["razon_social"].upper()
            )
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Cliente.DoesNotExist:
            pass
        return self.cleaned_data

facturacion/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate
from base.views import SinPrivilegios
from .models import Cliente, FacturaEnc, FacturaDet
from .forms import ClienteForm
from inventario.views import ProductoView
from inventario.models import Producto


class PerfilView(SinPrivilegios, ListView):
    permission_required="facturacion.view_cliente"
    model = Cliente
    template_name = "facturacion/clientes/perfil_cliente.html"

    def get(self, request,id, *args, **kwargs):
        cliente = Cliente.objects.filter(id=id)
        enc = FacturaEnc.objects.filter(cliente=id,pagado=True)
        context = {
            'cliente':cliente,
            'enc':enc,
        }
        return render(request, self.template_name, context)

class ClienteView(SinPrivilegios, ListView):
    model = Cliente
    template_name = "facturacion/clientes/cliente_list.html"
    context_object_name = "obj"
    permission_required="facturacion.view_cliente"


class VistaBaseCreate(SuccessMessageMixin, SinPrivilegios,
                      CreateView):
    context_object_name = 'obj'
    success_message = "Registro Agregado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.estado = True
        return super().form_valid(form)


class VistaBaseEdit(SuccessMessageMixin, SinPrivilegios,
                    UpdateView):
    context_object_name = 'obj'
    success_message = "Registro Actualizado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class ClienteNew(VistaBaseCreate):
    model = Cliente
    template_name = "facturacion/clientes/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy("facturacion:nueva_factura")
    permission_required = "facturacion.add_cliente"

    def post(self, request, *args, **kwargs):
        form = self.form_class()
        form_data = request.POST or None
        form_post = self.form_class(form_data)
        if request.method == 'POST':
            if 'rif' in request.POST:
                rif = request.POST['rif'].upper()
                desc = Cliente.objects.filter(rif=rif).exists()
                if desc ==  True:
                    messages.error(request,'Ya Existe un Cliente Registrado con Ese Rif.')
                    return redirect("facturacion:nueva_factura")
                else:
                    self.form_valid(form_post)
                    return redirect("facturacion:nueva_factura")
            return render(request, self.template_name, {'form': form})
    

class ClienteEdit(VistaBaseEdit):
    model = Cliente
    template_name = "facturacion/clientes/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy("facturacion:nueva_factura")
    permission_required = "facturacion.change_cliente"


class FacturaView(SinPrivilegios, ListView):
    model = FacturaEnc
    template_name = "facturacion/factura/factura_list.html"
    context_object_name = "obj"
    permission_required = "facturacion.view_facturaenc"

    def get_queryset(self):
        user = self.request.user
        # print(user,"usuario")
        qs = super().get_queryset()
        for q in qs:
            print(q.uc, q.id)

        if not user.is_superuser:
            qs = qs.filter(uc=user)

        for q in qs:
            print(q.uc, q.id)

        return qs

    def get(self, request):
        enc2 = FacturaEnc.objects.filter(pagado=True)
        enc = FacturaEnc.objects.filter(pagado=False)
        contexto = {'obj': enc, 'obj2': enc2}
        return render(request, self.template_name, contexto)


@login_required(login_url='/login/')
@permission_required('facturacion.change_facturaenc', login_url='base:sin_privilegios')
def facturas(request, id=None):
    try:
        template_name = 'facturacion/factura/facturas.html'
        detalle = {}
        clientes = Cliente.objects.filter(estado=True)
        if request.method == "GET":
            enc = FacturaEnc.objects.filter(pk=id).first()
            if id:
                if not enc:
                    messages.error(request, 'Factura No Existe')
                    return redirect("facturacion:lista_factura")
                usr = request.user
                if not usr.is_superuser:
                    if enc.uc != usr:
                        messages.error(
                            request, 'Factura no fue creada por usuario')
                        return redirect("facturacion:lista_factura")
            if not enc:
                encabezado = {
                    'id': 0,
                    'fecha': datetime.today(),
                    'cliente': 0,
                    'sub_total': 0.00,
                    'descuento': 0.00,
                    'total': 0.00,
                    'guia': "",
                    'numventa':""
                }
                detalle = None
            else:
                encabezado = {
                    'id': enc.id,
                    'fecha': enc.fecha,
                    'cliente': enc.cliente,
                    'sub_total': enc.sub_total,
                    'descuento': enc.descuento,
                    'total': enc.total,
                    'guia': enc.guia,
                    'numventa': enc.numventa,
                    'pagado': enc.pagado,
                    'tipo_pago': enc.tipo_pago
                }

            detalle = FacturaDet.objects.filter(factura=enc, estado=False)
            detalle2 = FacturaDet.objects.filter(factura=enc, estado=True)

            contexto = {"enc": encabezado, "det": detalle,
                        "clientes": clientes, "det2": detalle2}
            return render(request, template_name, contexto)

        if request.method == "POST":

            cliente = request.POST.get("enc_cliente")
            fecha = request.POST.get("fecha")
            guia = request.POST.get("guia")
            numventa = request.POST.get("numventa")
            cli = Cliente.objects.get(pk=cliente)

            if not id:
                enc = FacturaEnc(
                    cliente=cli,
                    fecha=fecha,
                    guia=guia,
                    numventa=numventa
                )
                if enc:
                    enc.save()
                    id = enc.id
            else:
                enc = FacturaEnc.objects.filter(pk=id).first()
                if enc:
                    enc.cliente = cli
                    enc.guia = guia
                    enc.numventa = numventa
                    enc.save()

            if not id:
                messages.error(
                    request, 'No Puedo Continuar No Pude Detectar No. de Factura')
                return redirect("facturacion:lista_factura")

            codigo = request.POST.get("codigo")
            cantidad = request.POST.get("cantidad")
            precio = request.POST.get("precio")
            s_total = request.POST.get("sub_total_detalle")
            descuento = request.POST.get("descuento_detalle")
            total = request.POST.get("total_detalle")

            prod = Producto.objects.get(codigo=codigo)
            det = FacturaDet(
                factura=enc,
                producto=prod,
                cantidad=cantidad,
                precio=precio,
                sub_total=s_total,
                descuento=descuento,
                total=total
            )

            if det:
                
                det.save()

            return redirect("facturacion:editar_factura", id=id)

        return render(request, template_name, contexto)
    except:
        messages.error(request, 'Debe ingresar los Datos Correctamente')
        return redirect("facturacion:editar_factura", id=id)


class ProductoView(ProductoView):
    template_name = "facturacion/factura/buscar_producto.html"


def borrar_detalle_factura(request, id):
    template_name = "facturacion/factura/factura_borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)
    if request.method == "GET":
        context = {"det": det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")
        user = authenticate(username=usr, password=pas)
        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")
        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = det.sub_total
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.estado = True
            det.user_borra = request.user.username
            det.save()
            return HttpResponse("ok")
        return HttpResponse("Usuario no autorizado")

    return render(request, template_name, context)


class FacturaEncDelete(SinPrivilegios, DeleteView):
    permission_required = "compra.delete_comprasdet"
    model = FacturaEnc
    template_name = "facturacion/factura/eliminar_enc.html"
    context_object_name = 'obj'
    success_message = "Compra Eliminada"
    success_url = reverse_lazy("facturacion:lista_factura")


def pago_factura(request, id):

facturacion/templates/facturacion/clientes/cliente_form.html
<div class="modal-dialog modal-md">
    <div class="modal-content">
        {% if obj %}
        <form role="form" id="frmCliente" action="{% url 'facturacion:editar_cliente' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form"  id="frmCliente" action="{% url 'facturacion:nuevo_cliente' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Cliente
                            {% if t %} En Factura {% endif %}
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <input type="hidden" name="id" id="id" class="form-class frmid">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-danger" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

{% if t %}
<script>
$("#frmCliente").submit(function( e ) {
    var frm = $('#frmCliente');
    $.ajax({
            type: frm.attr('method'),
            url: "{{request.path}}",
            data: frm.serialize(),
            success: function (data) {
                $("#id").val(data)
                console.log(data)
                cerrar_modal()
            },
            error: function(data,b,c) {
                alert(data);
                console.log(c)
            }
        });
        return false;
});

</script>
{% endif %}

facturacion/templates/facturacion/clientes/cliente_list.html
{% extends 'padre/base.html' %}

{% block page_content %}
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
        <div class="alert alert-info">No hay Clientes Registrados</div>
      {% endif %}
      <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-toolbar=".buttons-toolbar" data-locale="es-MX" data-sort-order="desc">
        <thead align="center">
          <th>Id</th>
          <th>Razon Social</th>
          <th>Rif</th>
          <th>Dirección</th>
          <th>Teléfono</th>
          <th>Email</th>
          <th class="all">Acciones</th>
        </thead>
        <tbody align="center">
          {% for item in obj %}
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.razon_social}}</td>
              <td>{{ item.rif }}</td>
              <td>{{ item.direccion }}</td>
              <td>{{ item.telefono }}</td>
              <td>{{ item.email }}</td>
              <td>
                <a
                  class="btn btn-sm btn-success btn-circle"
                  title="Ver perfil"
                  href="{% url 'facturacion:perfil_cliente' item.id%}"
                  ><i class="fas fa-user"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

facturacion/templates/facturacion/clientes/perfil_cliente.html
{% extends 'padre/base.html' %} 
{% block page_content %} 
    
<div class="row">
  <div class="col-md-12">
    <div class="card py-4 px-3"> 
      <div class="">
        {% for item in cliente %}
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="name fs-4">Razon Social: {{ item.razon_social }}</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd fs-5">RIF / C.I.: {{ item.rif }}</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd1 fs-5">Direccion Principal: {{ item.direccion }}</span> 
          </div>
        </div>
        {% if item.direccion2 == None %}
        {% else %}
        <div class="row">
          <div class="col-md-12 mb-2">
            <span class="idd1 fs-5">Direccion Secundaria: {{ item.direccion2 }}</span> 
          </div>
        </div>
        {% endif %}
        <div class="row">
          <div class="col-md-12">
            <div class="date fs-5"> <span class="join">Registrado: {{ item.fc|date:"d/m/Y" }}</span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mt-4">
            <a class="btn btn-primary btn-circle" title="Imprimir historial" href="{% url 'facturacion:imprimir_general_cliente' item.id %}" target="reportes">
              <i class="fas fa-print"></i> Imprimir historial</a>  
          </div>
        </div>
         
        </div>
        <div class="text mt-3"> 
          <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-toolbar=".buttons-toolbar" data-locale="es-MX" data-sort-order="desc">
            <thead align="center">
                <tr>
                    <th>No. Factura</th>
                    <th>Cliente</th>
                    <th>Fecha</th>
                    <th>Gastos Adic</th>
                    <th>Total</th>
                    <th>Pagado</th>
                    <th>Imprimir</th>
                </tr>
            </thead>
            <tbody align="center">
                {% for item2 in enc %}
                <tr>
                    <td>RM-F-{{ item2.id }}</td>
                    <td>{{ item2.cliente }}</td>
                    <td>{{ item2.fecha | date:"d/m/Y"  }}</td>
                    <td>{{ item2.descuento|floatformat:2 }}$</td>
                    <td>{{ item2.total|floatformat:2 }}$</td>
                    <td>{% if item2.pagado %}
                      <i class="fa fa-circle-check text-success"></i>
                    {% else %}
                      <i class="fa fa-circle-xmark text-danger"></i>
                    {% endif %}</td>
                    <td><a
                      class="btn btn-sm btn-success btn-circle"
                      title="Imprimir"
                      href="{% url 'facturacion:factura_imprimir_one' item2.id%}"
                      target="reportes"
                      ><i class="fas fa-print"></i
                    ></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
            
            {% endfor %}
          </div> 
        </div>
    </div>
  </div>
</div>
          
 {% endblock %}